### ISSUE TITLE
Project README.md

### ISSUE THREAD

**Issue by AndreMiras** [jarvis57/etheroll-bot#1]
Interesting, thanks for open sourcing this script.
Too bad that didn't work out by the way.
I think it would be great to add a little readme instruction in the project. Simply explain what betting strategy it follows (Martingale I guess), how to use..., e.g. adding private key to `.env`, command line to use and output example.
Keep it up!

**Comment by jarvisnn** [comment]
Thanks @AndreMiras. Just update it 💯
